Support specifying plugins or hooks when using rtlcss
elchininet/postcss-rtlcss pull request #327
Opened 2024-05-09 06:06 UTC by aleen42

2024-05-09 09:59 UTC, elchininet commented
Hi @aleen42,

It is always recommended to discuss the intention of creating a feature before working on it, just to avoid working in vain.

If you want to support plugins and hooks, it cannot be done in that way that you did and you cannot link plugins and hooks of `RTLCSS`. It will create confussion and it will be a source of issues because most of the things supported by `RTLCSS` will not work with this plugin.

`postcss-rtlcss` uses `RTLCSS` behind the scenes, but this does not mean that it runs `RTLCSS` in the entire `CSS` input. `RTLCSS` is used only on declarations, but it doesn‘t run in any other element (the CSS root element, the rules, at rules, comments, etc). This means that anything that a user sets inside `directives` will potentially fail, I think that the only thing that will work without issues is the `processors` property.

The same with hooks, as `RTLCSS` is not executed in the `CSS` root, most probably what `RTLCSS` users expect from a hook will not work with `postcss-rtlcss`. So, if you want to build hooks, most probably it should be built here from scratch (the same way the control directives and the `stringMap` option are built from scratch).

Please, refactor this following the next:

* Do not use the types from `RTLCSS`, create your own types. You need to test what works with the plugin and the things that don‘t work should be removed (most probably the only thing that will work will be the `processors` property).
* Do not link to the `RTLCSS` options because as the options will not work in the same way, it will create confussion.
* Create tests for any piece of code that you introduce.

Regards and thanks for contributing to the project.

2024-05-10 03:27 UTC, aleen42 commented
@elchininet Thanks for your review. I have eliminated the unnecessary hooks options because it seems we do not need to hook during processing CSS declarations via `postcss-rtlcss`. The plugin options have been renamed as `processDeclarationPlugins` which are currently only applied during processing declarations.

2024-05-10 09:02 UTC, elchininet requested changes

2024-05-13 16:04 UTC, elchininet requested changes

2024-05-15 15:08 UTC, elchininet commented
Hi @aleen42,
Looks good to me. Update the branch (I think that you may get some merge conflicts).
Regards

2024-05-20 14:44 UTC, elchininet commented on src/@types/index.ts
> +        value: Array<Object>
The linting job is failing, just change this `Objects` to `object` and it should fix the issue.

2024-05-21 07:56 UTC, elchininet approved these changes

2024-05-21 07:58 UTC, elchininet commented
@aleen42,
I think that it is ready to merge.
Thanks for your contribution. 
I'll release a new version when I have a chance. 
Regards 👍🏼

2024-05-21 23:30 UTC, merged

2024-05-22 22:06 UTC, elchininet commented
Hi @aleen42,
The feature has been released in version [5.3.0](https://www.npmjs.com/package/postcss-rtlcss/v/5.3.0).
Regards